Usar creation and authenticatoin. Some code on app.js and login.js wa…
Drleugim/soundX pull request #4
Opened 2021-03-05 19:18 UTC by Drleugim

This PR contains SNX-19_Create-User. There are changes to App.js and Login.js to reorganize and add the authentication function and the new pages (Welcome, UserCreated) that show up after the user creates an account, accesses account using credentials, and inputs credentials incorrectly.

https://user-images.githubusercontent.com/77938631/110162738-20f2b500-7dbd-11eb-839e-55c9fc4ef64b.mp4

2021-03-05 19:25 UTC, ht1204 approved these changes
Be careful with typos next time, and short description is better, rest is ok.

2021-03-05 21:28 UTC, simonhoyos requested changes

2021-03-05 21:28 UTC, simonhoyos commented on src/components/LoginForm/index.js
>               <button
Por html semántico si tenemos un elemento que va a ser una navegación es mejor usar un elemento `a`. Si lo que quieres es que el link se vea como un botón el resultado lo puedes lograr a tráves de CSS

2021-03-05 21:28 UTC, simonhoyos commented on src/pages/Login.js
> +  handleNewUser = e => {
Lo mismo que el comentario anterior la navegación debería tratar de hacerse con los elementos `a`

2021-03-05 21:28 UTC, simonhoyos commented on src/pages/Login.js
> +          email={email}
ojo con la identación del código. Los props debería tener una identación adicional

2021-03-05 21:28 UTC, simonhoyos commented on src/pages/UserCreated.js
> +    console.log(props)
No es buena idea dejar console.logs en el código

2021-03-05 21:28 UTC, simonhoyos commented on src/pages/Welcome.js
> +function Welcome (props) {
El componente UserCreated y Welcome están haciendo lo mismo. Es necesario tener los 2 componentes

2021-03-05 21:40 UTC, ht1204 requested changes
Please, consider Simon's commentaries.

2021-03-05 21:45 UTC, tanyalej commented on src/components/LoginForm/index.js
>               <button
@simonhoyos te refieres al botón de create user?

2021-03-05 21:52 UTC, simonhoyos commented on src/components/LoginForm/index.js
>               <button
Si, al botón que me lleva al formularío para crear un nuevo usuario

2021-03-05 22:00 UTC, Drleugim commented on src/pages/Welcome.js
> +function Welcome (props) {
Simón, la pagina Welcome eventualmente va a tener mas componentes. Por ahora se ve igual a UserCreated. No se si prefieras que la quitemos y creemos de nuevo cuando la necesitemos.

2021-03-05 22:45 UTC, Drleugim commented
@simonhoyos please review my new changes. Thanks!

2021-03-05 23:10 UTC, simonhoyos requested changes

2021-03-05 23:10 UTC, simonhoyos commented on src/components/LoginForm/index.js
> +            <Link to={`/welcome/${email}`}>Create user </Link>
poner el email del usuario en la url de esta forma no es muy recomendado. lo pasaría mejor o por query string o lo pasaría por un state del link usando https://reactrouter.com/web/api/Link/to-object

2021-03-06 18:18 UTC, Drleugim commented
@simonhoyos please review my new changes. Thanks!

2021-03-06 19:20 UTC, ht1204 requested changes
Please, consider @tanyalej  suggestions, thanks.

2021-03-06 19:20 UTC, ht1204 commented on src/App.js
> +        <Route path= "/welcome/newUser" component={Welcome}/>
Please, consider replace this change, instead, try this: `<Route exact path="/welcome/:id/" component={Welcome}/>` CC @tanyalej .

2021-03-06 19:20 UTC, ht1204 commented on src/App.js
> +        <Route path= "/welcome/newUser" component={Welcome}/>
Mock data doesn't work with your proposal change `<Route path= "/welcome/newUser" component={Welcome}/>` CC @tanyalej

2021-03-07 02:24 UTC, ht1204 approved these changes

2021-03-07 11:26 UTC, simonhoyos approved these changes

2021-03-07 18:10 UTC, merged