Connection FE to BE for user creation and login
Drleugim/soundX pull request #7
Opened 2021-03-16 21:51 UTC by Drleugim

In this PR, the BE was connected with the FE using axios. The FE now send the request to the BE and validates an existing user or creates a new user in the db. It is also important to note that there where some style changes made to the FE so to differentiate the signin page from the register page. This was done so to avoid confusion between the login option and register option.

2021-03-16 22:19 UTC, ht1204 approved these changes

2021-03-17 12:59 UTC, simonhoyos requested changes

2021-03-17 12:59 UTC, simonhoyos commented on src/App.js
> +      {/* <nav>
Es mejor no dejar código comentado en el código que va para dev/main esto se considera código muerto

2021-03-17 12:59 UTC, simonhoyos commented on src/components/LoginForm/index.js
>          <BackgroundSection>
Traten de configurar sus editores de texto de la misma forma. La identación en este archivo es de 1 tab mientras que en otros archivos es de 2 espacios

2021-03-17 12:59 UTC, simonhoyos commented on src/pages/Login/index.js
> +        baseURL: 'http://localhost:8000',
Es bueno almacenar esta url en una variable de entorno así la podemos cambiar fácilmente en el futuro

2021-03-17 12:59 UTC, simonhoyos commented on src/pages/Signup/index.js
> +          baseURL: 'http://localhost:8000',
Lo mismo que el comentario anterior

2021-03-17 13:30 UTC, Drleugim commented
@simonhoyos changes have been made according to comments. Please review again. Thank you!

2021-03-17 17:08 UTC, simonhoyos requested changes

2021-03-17 17:08 UTC, simonhoyos commented on .env
> +REACT_APP_SERVER_URL=http://localhost:8000
Este archivo debería ir ignorado. Lo puedes agregar al .gitignore y luego corres el comando `git rm --cached .env` para remover la referencia de git

2021-03-17 17:08 UTC, simonhoyos commented on src/components/LoginForm/index.js
> +	return (
Ojo se se duplicó la identación

2021-03-17 17:49 UTC, Drleugim commented on src/components/LoginForm/index.js
> +	return (
hmm no se porque pero modifico el setting para que solo haga un tab, me lo arregla, cierro el archivo, y cuando lo vuelvo a abrir me lo pone en doble tab nuevamente

2021-03-17 18:06 UTC, Drleugim commented on src/components/LoginForm/index.js
> +	return (
Listo ya encontré porqué pasa eso. Voy ha hablar con @tanyalej y @ht1204 para que todos tengamos el text editor configurado igual en cuanto a los tabs.

2021-03-17 19:03 UTC, simonhoyos approved these changes

2021-03-17 19:34 UTC, merged