Logout and URL direct access validation
Drleugim/soundX pull request #8
Opened 2021-03-18 22:47 UTC by tanyalej

1. Logout: implemented by using `<Link>` from ReactRouter and its `onClick` event. 
2. Direct access validation: **_Private routes_** implemented for url direct access validation to soundX pages

2021-03-19 12:52 UTC, simonhoyos requested changes

2021-03-19 12:52 UTC, simonhoyos commented on src/App.js
> +}
Podrías usar un solo componente PrivateRoute que reciba un prop to y ahí decides a dónde lo redireccionas. No habría necesidad de tener 2 componentes iguales

2021-03-21 22:01 UTC, simonhoyos approved these changes

2021-03-21 22:02 UTC, ht1204 approved these changes

2021-03-21 22:02 UTC, merged